services:
  lf-front:
    container_name: lf-front
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    volumes:
      - ./:/myapp
    ports:
      - '3200:3000'
    networks:
      - lifeplan-network

networks:
  lifeplan-network:
    external: true
