name: Rails CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup network
        run: docker network create lifeplan-network

      - name: Build Docker image
        run: docker compose build lf-front

      - name: Run yarn install
        run: docker compose run --rm lf-front yarn install

      - name: Run prettier
        run: docker compose run --rm lf-front yarn prettier_check

      - name: Run lint
        run: docker compose run --rm lf-front yarn lint_check
